# Generated by Django 4.2.27 on 2026-05-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to='cnic/'),
        ),
        migrations.AddField(
            model_name='user',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to='cnic/'),
        ),
        migrations.AddField(
            model_name='user',
            name='cnic_verified',
            field=models.CharField(choices=[('none', 'Not Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
