# Generated by Django 4.2.27 on 2026-05-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='crop_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
